name: Test Laravel Code

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, pdo, sqlite, mysql

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: |
          cp .env.example .env
          php artisan key:generate
          # testing ke liye sqlite use karo
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env

      - name: Cache Laravel configuration
        run: php artisan config:cache

      - name: Run syntax check
        run: find app -name "*.php" -print0 | xargs -0 -n1 php -l

      - name: Run tests
        run: php artisan test --env=testing
